### ISSUE TITLE
error during running voice assistant

### ISSUE THREAD

**Issue by lameTookan** [libraryofcelsus/Aetherius_AI_Assistant#10]
```
Traceback (most recent call last):
  File "C:\AlexsNewJazz\ai\ai-assist\main.py", line 86, in <module>
    main_menu()
  File "C:\AlexsNewJazz\ai\ai-assist\main.py", line 55, in main_menu
    function()
  File "C:\AlexsNewJazz\ai\ai-assist\scripts/OpenAi_General_Chatbot.py", line 48, in OpenAi_General_Chatbot
    function()
  File "C:\AlexsNewJazz\ai\ai-assist\scripts/OpenAi_General_Chatbot/GPT_4_Voice_Assistant.py", line 442, in GPT_4_Voice_Assistant
    counter2 += 1
UnboundLocalError: local variable 'counter2' referenced before assignment
```

**Comment by libraryofcelsus** [comment]
Currently cleaning up the code, I should have updated scripts with this fixed later today or tomorrow.

**Comment by libraryofcelsus** [comment]
Fixed!
