### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by darkanubis0100** [libraryofcelsus/Aetherius_AI_Assistant#14]
```
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\Dev\Aetherius_AI_Assistant\main.py", line 96, in <module>
    main_menu()
  File "C:\Users\Administrator\Documents\Dev\Aetherius_AI_Assistant\main.py", line 56, in main_menu
    function()
  File "C:\Users\Administrator\Documents\Dev\Aetherius_AI_Assistant\scripts/OpenAi_General_Chatbot.py", line 48, in OpenAi_General_Chatbot
    function()
  File "C:\Users\Administrator\Documents\Dev\Aetherius_AI_Assistant\scripts/OpenAi_General_Chatbot/GPT_4_Tasklist_Web_Scrape.py", line 496, in GPT_4_Tasklist_Web_Scrape
    int_conversation.append({'role': 'assistant', 'content': "MEMORIES: %s;\n%s;\n%s;\n\n%s'S INNER THOUGHTS: %s;\nHEURISTICS: %s;\nUSER MESSAGE: %s;\nWEBSCRAPE SAMPLE: %s\nIn a single paragraph, interpret the user, %s's message as %s in third person by creating an intuitive plan on what information needs to be researched from the webscrape, even if the user is uncertain about their own needs.;\nINTUITION: " % (db_search_4, db_search_5, db_search_12, bot_name, output_one, db_search_13, a, int_scrape, username, bot_name)})
NameError: name 'db_search_13' is not defined. Did you mean: 'db_search_1'?
```

Whenever I try to start a chat using the "GPT-4 Web Scrape" configuration I get this error.

First the web scraping is done and then it allows you to start the chat, that's when you enter something that you get the error.

**Comment by libraryofcelsus** [comment]
Change 13 to 15 to fix.  Should already be fixed in gui.

**Comment by darkanubis0100** [comment]
> Change 13 to 15 to fix. Should already be fixed in gui.

Thank you, it was indeed solved
